#!/bin/bash
# 00-=asswords
# aoneill - 02/19/16

EXEC=$(test "$_" != "$0"; echo $?)
SUPPORT="$1"
GLOBALS="$2"

source "$GLOBALS"

function init() {
  section Passwords

  echo -e "\
WARNING: This section is sensitive! I will ask you for various passwords,
  and show them to you as you type. This so that you can verify the passwords
  you supply for correctness, as they will be used later to configure your
  system.

Make sure no one is watching!\n"

  _pw_record "Arch Linux" "this machine"
  _pw_record "Github" "@github.com"
  _pw_record "Andrew" "@andrew.cmu.edu"

  echo "
For your viewing pleasure, I have places your sensitive information in:
  $PASSWD_FILE

This will be removed at the end of setup"
} 

function _pw_record() {
  prog=$1
  extra=$2
  if [[ $extra != "" ]]
  then
    extra=" ($extra)"
  fi

  echo -n "Username for ${prog}${extra}: "
  read user
  echo -n "Password: "
  read password
  
  echo "$(echo $prog | sed -e 's/ //g' | tr '[:upper:]' '[:lower:]')" \
    >> $PASSWD_FILE
  echo "$user" >> $PASSWD_FILE
  echo "$password" >> $PASSWD_FILE
}

function pw_lookup() {
  prog="$(echo $1 | sed -e 's/ //g' | tr '[:upper:]' '[:lower:]')"
  tmp=$(mktemp)

  echo $PASSWD_FILE | grep -A 3 "$prog" > $tmp
  user=$(cat $tmp | sed -e '2q;d')
  passwd=$(cat $tmp | sed -e '3q;d')

  echo -ne "$user\n$passwd"
  rm $tmp
}

function pw_screwup() {
  prog="$(echo $1 | sed -e 's/ //g' | tr '[:upper:]' '[:lower:]')"
  
  tmp=$(mktemp)
  pw_lookup $prog > $tmp

  user=$(cat $tmp | sed -e '1q;d')
  passwd=$(cat $tmp | sed -e '2q;d')

  echo "\
ERROR: You gave me incorrect credentials for $1!
You gave me ($user, $passwd) earlier.
Please give me the correct combination:"
  echo -n "Username for ${prog}: "
  _pw_record user
  echo -n "Password: "
  _pw_record password
  
  cat $PASSWD_FILE | sed -e "/^$prog/,+3d" > $tmp
  mv $tmp $PASSWD_FILE

  echo "$(echo $prog | sed -e 's/ //g' | tr '[:upper:]' '[:lower:]')" \
    >> $PASSWD_FILE
  echo "$user" >> $PASSWD_FILE
  echo "$password" >> $PASSWD_FILE
}

[[ "$EXEC" == "1" ]] && init
