#!/bin/bash
# 10-accounts
# aoneill - 03/09/16

SUPPORT="$CWD/support"
GLOBALS="$SUPPORT/globals"

source "$GLOBALS"

# Use utilities here
source $SUPPORT/*-passwords

function init() {
  section Accounts

  echo "Configuring user account"
  tmp=$(mktemp)
  pw_lookup archlinux | tee $tmp >/dev/null
  user=$(cat $tmp | head -n 1)
  password=$(cat $tmp | tail -n 1)

  # Initialize the HOME_DIR variable
  homedir=/home/$user 
  echo "$homedir" > $HOMEDIR_FILE

  groupadd -f sudo
  useradd -d $homedir -m -G sudo $user
  echo "$user:$password" | chpasswd
  
  echo "Configuring Github account"
  pw_lookup github | tee $tmp >/dev/null
  user=$(cat $tmp | head -n 1)
  password=$(cat $tmp | tail -n 1)

  # Generate RSA Key
  mkdir -p $homedir/.ssh
  ssh-keygen -t rsa -f $homedir/.ssh/id_rsa -N ''

  curl -u "$user:$password" "https://api.github.com" | grep "Bad credentials"
  while [[ "$?" == "0" ]]
  do
    pw_screwup github
    pw_lookup github | tee $tmp >/dev/null
    user=$(cat $tmp | head -n 1)
    password=$(cat $tmp | tail -n 1)
    curl -u "$user:$password" "https://api.github.com" | grep "Bad credentials"
  done
  curl -u "$user:$password" \
    --data "{\"title\": \"$(hostname)\", \
             \"key\": \"$(cat $homedir/.ssh/id_rsa.pub)\"}" \
    "https://api.github.com/user/keys"
} 

function acc_get_home() {
  cat $HOMEDIR_FILE
}

EXEC=$(test "${BASH_SOURCE[0]}" != "${0}"; echo $?)
[[ "$EXEC" == "1" ]] && init $@

