#!/bin/bash
# 31-resources
# aoneill - 03/09/16

PRE_DIR="$CWD/pre-setup"
GLOBALS="$PRE_DIR/globals"

source "$GLOBALS"

# Use utilities here
source $PRE_DIR/*-passwords

# Install all the packages needed
function init() {
  section Resources

  echo "Downloading additional resources"
  cd $RESOURCES
  git clone --recursive git@github.com:/alexoneill/config.git
}

# Execute init (passing arguments) if we are not sourced
EXEC=$(test "${BASH_SOURCE[0]}" != "${0}"; echo $?)
[[ "$EXEC" == "1" ]] && init $@
